In [44]:
import requests
from bs4 import BeautifulStoneSoup
import xml.etree.ElementTree as ET
import json

url = 'http://apis.data.go.kr/1471000/MdcinGrnIdntfcInfoService01/getMdcinGrnIdntfcInfoList01'
params ={'serviceKey' : 'cdBrRYhpl2+/cPvsFcTDZ64C2g8cgGPFw8qA5omyEL3mrKFuF8MPaV/B6PpqUGdMaORPLU9l8A7Wg9TBvt0O1g==', 
        # 'item_name' : '가나릴정(이토프리드염산염)',     # 제품명
        # 'entp_name' : '영풍제약(주)',                                # 업체명
        'item_seq' : '200402915',                                   # 일련번호
        # 'img_regist_ts' : '20100326',                               # 이미지 생성일
        'pageNo' : '1',                                             # 페이지
        'numOfRows' : '3',                                          # 한 페이지 결과 수
        # 'edi_code' : '',                                          # 보험코드 
        'type' : 'json'                                              # 데이터 포멧
        }

response = requests.get(url, params=params)
a = response.content
# soup = BeautifulStoneSoup(response.content, 'xml.parser')
# soup

# def _pretty_print(current, parent=None, index=-1, depth=0):
#     for i, node in enumerate(current):
#         _pretty_print(node, current, i, depth + 1)
#     if parent is not None:
#         if index == 0:
#             parent.text = '\n' + ('\t' * depth)
#         else:
#             parent[index - 1].tail = '\n' + ('\t' * depth)
#         if index == len(parent) - 1:
#             current.tail = '\n' + ('\t' * (depth - 1))

# tree = ET.parse(response.content)

# _pretty_print(tree.getroot())

# ET.dump(tree)

# root = ET.fromstring(response.content)
# for child in root:
#      print(child.tag, child.attrib)

a

b'{"header":{"resultCode":"00","resultMsg":"NORMAL SERVICE."},"body":{"pageNo":1,"totalCount":1,"numOfRows":3,"items":[{"ITEM_SEQ":"200402915","ITEM_NAME":"\xea\xb0\x80\xeb\x82\x98\xeb\xa6\xb4\xec\xa0\x95(\xec\x9d\xb4\xed\x86\xa0\xed\x94\x84\xeb\xa6\xac\xeb\x93\x9c\xec\x97\xbc\xec\x82\xb0\xec\x97\xbc)","ENTP_SEQ":"19630009","ENTP_NAME":"\xec\x98\x81\xed\x92\x8d\xec\xa0\x9c\xec\x95\xbd(\xec\xa3\xbc)","CHART":"\xed\x9d\xb0\xec\x83\x89 \xec\x9b\x90\xed\x98\x95\xec\x9d\x98 \xed\x95\x84\xeb\xa6\x84\xec\xbd\x94\xed\x8c\x85\xec\xa0\x95","ITEM_IMAGE":"https://nedrug.mfds.go.kr/pbp/cmn/itemImageDownload/1ONpCOpRdab","PRINT_FRONT":"Y50","PRINT_BACK":null,"DRUG_SHAPE":"\xec\x9b\x90\xed\x98\x95","COLOR_CLASS1":"\xed\x95\x98\xec\x96\x91","COLOR_CLASS2":null,"LINE_FRONT":null,"LINE_BACK":null,"LENG_LONG":"7.1","LENG_SHORT":"7.1","THICK":"3.6","IMG_REGIST_TS":"20081219","CLASS_NO":"02390","CLASS_NAME":"\xea\xb8\xb0\xed\x83\x80\xec\x9d\x98 \xec\x86\x8c\xed\x99\x94\xea\xb8\xb0\xea\xb4\x80\xec\x9a\xa9\x

In [48]:
b = json.loads(a)
b

{'header': {'resultCode': '00', 'resultMsg': 'NORMAL SERVICE.'},
 'body': {'pageNo': 1,
  'totalCount': 1,
  'numOfRows': 3,
  'items': [{'ITEM_SEQ': '200402915',
    'ITEM_NAME': '가나릴정(이토프리드염산염)',
    'ENTP_SEQ': '19630009',
    'ENTP_NAME': '영풍제약(주)',
    'CHART': '흰색 원형의 필름코팅정',
    'ITEM_IMAGE': 'https://nedrug.mfds.go.kr/pbp/cmn/itemImageDownload/1ONpCOpRdab',
    'PRINT_FRONT': 'Y50',
    'PRINT_BACK': None,
    'DRUG_SHAPE': '원형',
    'COLOR_CLASS1': '하양',
    'COLOR_CLASS2': None,
    'LINE_FRONT': None,
    'LINE_BACK': None,
    'LENG_LONG': '7.1',
    'LENG_SHORT': '7.1',
    'THICK': '3.6',
    'IMG_REGIST_TS': '20081219',
    'CLASS_NO': '02390',
    'CLASS_NAME': '기타의 소화기관용약',
    'ETC_OTC_NAME': '전문의약품',
    'ITEM_PERMIT_DATE': '20041029',
    'FORM_CODE_NAME': '필름코팅정',
    'MARK_CODE_FRONT_ANAL': '',
    'MARK_CODE_BACK_ANAL': '',
    'MARK_CODE_FRONT_IMG': '',
    'MARK_CODE_BACK_IMG': '',
    'ITEM_ENG_NAME': 'GANARILLTAB.(ITOPRIDEHCl)',
    'CHANGE_DATE': '20210624',

In [2]:
import pandas as pd
import urllib
import requests
from pathlib import Path

data = pd.read_csv('D:\download\OpenData_PotOpenTabletIdntfcC20230209.csv')
data = data.iloc[:10,:]
# list_a = data['큰제품이미지'][:10]
columns = ['품목일련번호', '품목명', '업소일련번호', '업소명', '큰제품이미지', '의약품제형', '색상앞', '분류명', '전문일반구분']
# data[columns]['품목일련번호']

# data[['품목일련번호', '큰제품이미지']]

# 이미지 다운로드
# for idx, row in data.iterrows():
#     urllib.request.urlretrieve(row['큰제품이미지'], str(row['품목일련번호'])+'.png')
    # print(idx, row['품목일련번호'], row['큰제품이미지'])

def image_download(row):
    urllib.request.urlretrieve(row['큰제품이미지'], str(row['품목일련번호'])+'.png')

In [3]:
pd.read_csv('D:\download\OpenData_PotOpenTabletIdntfcC20230209.csv')

품목일련번호                      품목명    업소일련번호         업소명  \
0      200808876  가스디알정50밀리그램(디메크로틴산마그네슘)  19540006     일동제약(주)   
1      200808877       페라트라정2.5밀리그램(레트로졸)  19560004     (주)유한양행   
2      200808948         졸뎀속붕정(졸피뎀타르타르산염)  20080422     보령제약(주)   
3      200809076    가스프렌정(모사프리드시트르산염이수화물)  19760002     경동제약(주)   
4      200809361               바르탄정(발사르탄)  19870002      (주)휴온스   
...          ...                      ...       ...         ...   
24867  202001764         비엘아세틸캡슐(아세틸시스테인)  20163305    (주)라이트팜텍   
24868  201907100           삼성피나스테리드정1밀리그램  19540005     삼성제약(주)   
24869  202204507        베포틴서방정(베포타스틴베실산염)  19550015  (주)동구바이오제약   
24870  202204282   하이퍼벤서방정90밀리그램(딜티아젬염산염)  19860001  한국휴텍스제약(주)   
24871  202204200                    폰트미네정  19550001     이연제약(주)   

                          성상  \
0                 녹색의원형필름코팅정   
1              어두운황색의원형필름코팅정   
2                흰색의원형구강붕해정제   
3         분할선을가진흰색의장방형필름코팅정제   
4               엷은적색의원형필름코팅정   
...                      ...   
24867     흰색의분말이충진된상|하부흰색의캡슐   
24868  황갈색의양면이볼록한팔각형모양의필름코팅정   
24869             흰색의원형필름코팅정   
24870          흰색또는유백색의원형서방정   
24871          연한파란색의원형필름코팅정   

                                                  큰제품이미지    표시앞  표시뒤 의약품제형  \
0      https://nedrug.mfds.go.kr/pbp/cmn/itemImageDow...    IDG    -    원형   
1      https://nedrug.mfds.go.kr/pbp/cmn/itemImageDow...     YH   LT    원형   
2      https://nedrug.mfds.go.kr/pbp/cmn/itemImageDow...      -    -    원형   
3      https://nedrug.mfds.go.kr/pbp/cmn/itemImageDow...     KD  분할선   장방형   
4      https://nedrug.mfds.go.kr/pbp/cmn/itemImageDow...  V분할선T  HS8    원형   
...                                                  ...    ...  ...   ...   
24867  https://nedrug.mfds.go.kr/pbp/cmn/itemImageDow...  BL200    -   장방형   
24868  https://nedrug.mfds.go.kr/pbp/cmn/itemImageDow...     SS   F1   팔각형   
24869  https://nedrug.mfds.go.kr/pbp/cmn/itemImageDow...    DKC    -    원형   
24870  https://nedrug.mfds.go.kr/pbp/cmn/itemImageDow...     HT   90    원형   
24871  https://nedrug.mfds.go.kr/pbp/cmn/itemImageDow...     ry    -    원형   

      색상앞  ...    품목허가일자     제형코드명 표기내용앞 표기내용뒤 표기이미지앞 표기이미지뒤  표기코드앞 표기코드뒤  \
0      연두  ...  20080820       당의정     -     -      -      -      -     -   
1      노랑  ...  20080820     필름코팅정     -     -      -      -      -     -   
2      하양  ...  20080825        정제     -     -      -      -      -     -   
3      하양  ...  20080828     필름코팅정     -     -      -      -      -     -   
4      분홍  ...  20080908     필름코팅정     -     -      -      -      -     -   
...    ..  ...       ...       ...   ...   ...    ...    ...    ...   ...   
24867  하양  ...  20200313  경질캡슐제|산제     -     -      -      -      -     -   
24868  분홍  ...  20191007     필름코팅정     -     -      -      -      -     -   
24869  하양  ...  20221216     필름코팅정     -     -      -      -      -     -   
24870  하양  ...  20221128       서방정     -     -      -      -      -     -   
24871  파랑  ...  20221121     필름코팅정     -     -      -      -      -     -   

           변경일자 Unnamed: 29  
0             -         NaN  
1             -         NaN  
2             -         NaN  
3      20211223         NaN  
4             -         NaN  
...         ...         ...  
24867  20220929         NaN  
24868  20210813         NaN  
24869         -         NaN  
24870         -         NaN  
24871         -         NaN  

[24872 rows x 30 columns]

In [3]:
# pip install pillow
# !pip install pandas
# !pip install numpy

In [4]:
# import cv2
import numpy as np
from PIL import Image
import pandas as pd
from glob import glob
import os

# 이미지 csv 저장
1. 이미지 불러오기
2. 이름 추출하기
3. 이미지 numpy 형식으로 변경하기
4. csv 만들기
5. 기존의 csv파일에 넣기

* multiprocessing을 이용해 빠르게 진행하려고 함
  -> 메모리 부족으로 실패
  -> batch_size를 이용하여 32개 단위로 나눠서 진행
  -> 

In [6]:

pill_image_list = []
pill_images = glob('./pill_images/*')
i = 1
for pill in pill_images:
    idx = os.path.basename(pill)[:-4]
    img = Image.open(pill)
    # numpy 배열로 변경하기
    x = np.array(img)

    pill_image_dict = {
        '품목일련번호': idx,
        '이미지': x
    }
    pill_image_list.append(pill_image_dict)
pill_image_csv = pd.DataFrame(pill_image_list)
pill_image_csv

Empty DataFrame
Columns: []
Index: []

In [8]:
# pill_image_csv = pd.DataFrame()
pill_image_list = []
pill_images = glob('./pill_images/*')
for pill in pill_images:
    # 이미지 제목(품목일련번호)
    idx = os.path.basename(pill)[:-4]
    # 이미지 불러오기
    img = Image.open(pill)
    # numpy 배열로 변경하기
    x = np.array(img)

    pill_image_dict = {
        '품목일련번호': idx,
        '이미지': x
    }
    pill_image_list.append(pill_image_dict)
pill_image_csv = pd.DataFrame(pill_image_list)
pill_image_csv

품목일련번호                                                이미지
0      195900001  [[[184, 199, 218], [187, 202, 221], [188, 203,...
1      195900032  [[[191, 206, 225], [191, 206, 225], [191, 206,...
2      195900043  [[[191, 206, 225], [191, 206, 225], [191, 206,...
3      196000001  [[[191, 206, 225], [191, 206, 225], [191, 206,...
4      196000003  [[[191, 206, 225], [191, 206, 225], [191, 206,...
...          ...                                                ...
14478  201405793  [[[166, 193, 236], [166, 193, 236], [166, 193,...
14479  201405795  [[[165, 192, 235], [165, 192, 235], [165, 192,...
14480  201405796  [[[166, 193, 236], [166, 193, 236], [166, 193,...
14481  201405797  [[[166, 193, 236], [166, 193, 236], [166, 193,...
14482  201405798  [[[166, 193, 236], [166, 193, 236], [166, 193,...

[14483 rows x 2 columns]

In [ ]:
pill_image_csv.to_csv('piil.csv', encoding='utf-8-sig')

In [9]:
img = Image.open('./pill_images/195900001.png')
# img.show()

x = np.array(img)
print(x)
print(x.shape)

# x_2 = np.asarray(img)
# print(x_2)
# print(x_2.shape)

img_2 = Image.fromarray(x)
img_2.show()


[[[184 199 218]
  [187 202 221]
  [188 203 222]
  ...
  [187 202 221]
  [187 202 221]
  [184 199 218]]

 [[187 202 221]
  [191 206 225]
  [191 206 225]
  ...
  [190 205 224]
  [191 206 225]
  [188 203 222]]

 [[188 203 222]
  [191 206 225]
  [191 206 225]
  ...
  [190 205 224]
  [191 206 225]
  [188 203 222]]

 ...

 [[121 140 173]
  [121 140 173]
  [121 140 173]
  ...
  [121 140 173]
  [121 140 173]
  [121 140 173]]

 [[121 140 172]
  [121 140 172]
  [121 140 172]
  ...
  [121 140 172]
  [121 140 172]
  [121 140 172]]

 [[121 140 172]
  [121 140 172]
  [121 140 172]
  ...
  [121 140 172]
  [121 140 172]
  [121 140 172]]]
(426, 780, 3)
